### ISSUE TITLE
Certain functions do not overload counterparts in `LinearAlgebra`

### ISSUE THREAD

**Issue by BenjaminRemez** [matthias314/Modulo2.jl#7]
Some functions (so far I noticed `rank` and `inv`) do not overload their counterparts in `LinearAlgebra`. `using Modulo2, LinearAlgebra` pollutes the namespace with e.g. two `rank` functions that must be disambiguated and thus one cannot dispatch on the type of the matrix. Is this intentional? If not, I am happy to commit a fix.

**Comment by matthias314** [comment]
`inv` is defined in `Base`, so there should be no problem. For `rank`, however, this is an oversight. I've just fixed it on master. Thanks for reporting it!
